networks:
  quic-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  # Main QUIC Load Balancer
  quic-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: quic-server:latest
    container_name: quic-server
    ports:
      - "9443:9443/tcp"  # HTTP/2 server
      - "9443:9443/udp"  # QUIC/HTTP3 server
      - "8080:8080"      # HTTP server
    networks:
      - quic-network
    environment:
      - GO_ENV=production
      - BACKEND_1_URL=http://quic-backend1:8000
      - BACKEND_2_URL=http://quic-backend2:8000
      - BACKEND_3_URL=http://quic-backend3:8000
    restart: unless-stopped
    depends_on:
      - backend1
      - backend2
      - backend3

  # Backend Services
  backend1:
    image: python:3.11-alpine
    container_name: quic-backend1
    ports:
      - "8081:8000"
    networks:
      - quic-network
    volumes:
      - ./static:/app/static
    working_dir: /app
    command: python3 -m http.server 8000 --directory static
    restart: unless-stopped

  backend2:
    image: python:3.11-alpine
    container_name: quic-backend2
    ports:
      - "8082:8000"
    networks:
      - quic-network
    volumes:
      - ./static:/app/static
    working_dir: /app
    command: python3 -m http.server 8000 --directory static
    restart: unless-stopped

  backend3:
    image: python:3.11-alpine
    container_name: quic-backend3
    ports:
      - "8083:8000"
    networks:
      - quic-network
    volumes:
      - ./static:/app/static
    working_dir: /app
    command: python3 -m http.server 8000 --directory static
    restart: unless-stopped

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: quic-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/quic_rules.yml:/etc/prometheus/quic_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - quic-network
    restart: unless-stopped
    depends_on:
      - quic-server

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: quic-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - quic-network
    restart: unless-stopped
    depends_on:
      - prometheus

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: quic-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - quic-network
    restart: unless-stopped
